apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: fluentbit-pdb
  namespace: kube-system
spec:
  minAvailable: 3
  selector:
    matchLabels:
      k8s-app: fluentbit-gke        
